default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bonus_cards_api_development

test:
  <<: *default
  database: bonus_cards_api_test

production:
  <<: *default
  database: bonus_cards_api_production
  username: bonus_cards_api
  password: <%= ENV["BONUS_CARDS_API_DATABASE_PASSWORD"] %>
