name: "Ruby on Rails CI"
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://testuser:testpass@localhost:5432/testdb

    steps:
      - name: Check if owner
        run: |
          IFS='/' read -ra ORG_REPO <<< "$GITHUB_REPOSITORY"
          if [ "$GITHUB_ACTOR" != "octo-organization-test[bot]" ]; then
            echo "Only the owner can run this action."
            exit 1
          fi
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Cleanup repository
        run: rm -rf spec setup spec-setup
      - name: Checkout private specs
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            spec
            setup
          repository: TestEducationAlexey/public_spec
          token: ${{ secrets.GITHUB_TOKEN }}
          path: spec-setup
      - name: Move specs and setup
        run: mv spec-setup/spec/ spec/ && mv spec-setup/setup/ setup/
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
      - name: Setup gems
        run: ruby setup/install_check.rb
      - name: Set up database schema
        run: bin/rails db:schema:load
      - name: Run tests
        run: bundle exec rspec
